### ISSUE TITLE
query placement fluidity

### ISSUE THREAD

**Issue by chklopp** [FadyMohareb/mapoptics#1]
Thank you for mapoptics!
Moving queries around in the reference view is very slow and cpu intensive (my laptop fan gets loud).
Is there a way to speed up?

**Comment by glynnmartin-cranfield** [comment]
Hi chklopp, today we have released a MapOptics Beta version, that should address the cpu intensity you have been experiencing.

**Comment by chklopp** [comment]
Hi glynnmartin-cranfield, thank you but I do not find any improvement in the response time or cpu load.

Here are my OS and java versions 

NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

**Comment by glynnmartin-cranfield** [comment]
Hi chklopp, thanks for your feedback.  Can I just confirm you are using the MapOptics_2020_GP.jar from the MapOptics_Beta branch?
If that is the case I would interested in knowing the number of query contigs related to the reference contig that is causing cpu strain, as we haven't experienced this issue during development of the Beta.

**Comment by chklopp** [comment]
Here is my command line
java -jar mapOptics_2020_GP.jar

**Comment by chklopp** [comment]
reference maps : 106
query maps : 11
lines in the xmap file : 54

**Comment by glynnmartin-cranfield** [comment]
Thanks again for all the information, is there any chance you would be able to share this dataset with us? As we would be keen to work on these data and solve this issue for you and others.
If not, could you share a screen shot of reference view?

**Comment by chklopp** [comment]
I can share the data through a private link if you send me an email at christophe dot klopp at inrae dot fr

**Comment by chklopp** [comment]
I've just installed java build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1 and mapOptics_2020_GP fluidity improved a lot.

**Comment by glynnmartin-cranfield** [comment]
Hi chklopp, thanks for the dataset, we have tested your data on Ubuntu versions here and had differing lag but up to a maximum of 2 seconds when moving query contigs in Reference View, we didn't see a significant impact on CPU usage.
I am glad to here a new java build has helped improved fluidity and this may be something we can state in our future releases. I appreciate your patience and collaboration on this.
